### ISSUE TITLE
Undefined variable / offset warnings

### ISSUE THREAD

**Issue by dregad** [vincentsels/ProjectManagement#1]
I noticed a number of warnings and system notices while navigating the plugin's pages, including but not limited to

APPLICATION WARNING 300 String "plugin_ProjectManagement_last_months" not found.
SYSTEM NOTICE: Undefined variable: t_num_recent
SYSTEM NOTICE: Undefined variable: t_val
SYSTEM NOTICE: Undefined offset: 0
SYSTEM NOTICE: Undefined variable: t_todo
SYSTEM NOTICE: Undefined offset: 20

Note - In my dev env, I generally set errors display like this in config_inc.php:
$g_display_errors = array(
    E_WARNING => 'halt',
    E_NOTICE => 'inline',
    E_USER_ERROR => 'halt',
    E_USER_WARNING => 'halt',
    E_USER_NOTICE => 'halt'
);

**Comment by vincentsels** [comment]
Dregad, in your opinion, do you think that in this situation it's ok to just suppress the notices (eg see branch suppress-notices), or should i always check with isset (see branch fix-notices) ? Imo it makes the code less readable and bigger without added value. For the 'resource allocation' page this is even much more so.

**Comment by vincentsels** [comment]
Wouldn't adding the check everywhere even make the code slower ?

**Comment by dregad** [comment]
Well this might turn into a philosophical debate ;-)

Some people advocate that PHP is a softly typed language, and that those warnings are only here to help you and can be disregarded.

Others believe that warnings are issued for a reason and should be corrected. If you're using a variable, then it should be properly initialized first. I'm more part of that group, but I guess that probably comes from my background programming in C/C++ and other strongly typed languages where you have no choice in the matter.

As you rightly pointed out, fixing these warnings can make the code less readable and more complex. In some cases it's a better and easier alternative to properly initialize the variables first, but here considering that you're building dynamic arrays, it may not be the best option. Maybe suppressing the errors is the better solution here.

About performance, yes there is a small hit of course. The only way to really know how bad that is, is to run a benchmark. Interesting reading: http://vega.rd.no/post/5222122337/php-performance-error-suppression

At the end of the day, on a Prod system, warning and notices should be suppressed anyway; but I personnally spend most of my time doing development with error reporting turned on, and I really don't like seeing pages full of warnings. 

Just my 2 cents. Your code, your call :-)

**Comment by vincentsels** [comment]
Thanks for your 2 cents ;) I think I fixed or suppressed them all now.
