### ISSUE TITLE
Issues with MSSQL database

### ISSUE THREAD

**Issue by dsienkiewicz** [vincentsels/ProjectManagement#12]
Hi,
I'd like to report issues with ProjectManagement plugin on MS SQL database.

Issues are mainly caused by differences beetween MySQL and MS SQL dialect.

First:
in MS SQL it's impossible to create SELECT clause with GROUP BY, where in GROUP BY you have fields not included in SELECT clause.
Second:
Aliases in WHERE or GROUP BY are not allowed. If you have query like SELECT b.Id, b.due_date as date FROM bug_table b WHERE date = $somedate, you should use WHERE b.due_date instead.

Below is my fix-list, with file name and line number fixed. I'm not sure, if I clearly understood the meaning of that queries, so correct my if I'm wrong.

file: time_registration_page.php
line: 21
$t_query_recent           = "SELECT TOP $t_const_recently_visited b.last_updated, b.handler_id, b.project_id, p.name as project_name,
                            c.id as category_id, c.name as category_name, b.id as bug_id, b.summary as bug_summary, b.status,
                            (SELECT SUM(minutes) FROM $t_work_table w WHERE w.bug_id = b.id AND minutes_type = $t_const_done) as done
                             FROM $t_bug_table b
                             LEFT JOIN $t_project_table p ON b.project_id = p.id
                             LEFT JOIN $t_category_table c ON b.category_id = c.id
                            WHERE b.id IN ( $t_recently_visited )
                            ORDER BY b.last_updated DESC";

line: 35
$t_query_registered_day  = "SELECT b.id as bug_id, sum(w.minutes) as minutes, max(w.timestamp) as timestamp
                             FROM $t_work_table w JOIN $t_bug_table b ON w.bug_id = b.id
                            WHERE w.user_id = $t_user
                              AND w.book_date = $t_today
                              AND w.minutes_type = 1
                            GROUP BY b.id
                            ORDER BY timestamp DESC";

file: report_resource_progress_page.php
line: 124
    $t_query = "SELECT pc.id as project_id, pc.name as project_name, c.id as category_id, c.name as category_name,
                       b.id, b.handler_id, b.date_submitted, sum(w.minutes) as minutes
                  FROM $t_work_table w
                  JOIN $t_bug_table b ON w.bug_id = b.id
                  JOIN $t_project_table pc ON b.project_id = pc.id
                  JOIN $t_category_table c ON b.category_id = c.id
                  JOIN $t_res_table r ON b.handler_id = r.user_id
                 WHERE w.book_date BETWEEN $t_release_date_previous AND $t_release_date_target
                   AND w.minutes_type = $t_const_done
                   AND b.handler_id <> 0
                   AND b.target_version <> '$f_target_version'
                   AND ($f_user_id = $t_const_all_users OR b.handler_id = $f_user_id)
                   AND NOT EXISTS
                   (
                   SELECT 1
                     FROM $t_res_unav_table u
                    WHERE u.user_id = w.user_id
                      AND w.book_date between u.start_date and u.end_date
                      AND u.include_work = 0
                   )
                 GROUP BY pc.id, pc.name, c.id, c.name, b.id, b.handler_id, b.date_submitted
                 ORDER BY b.handler_id, b.date_submitted";

file: ProjectManagementAPI.php
line: 684
    $t_query = "SELECT pp.id as parent_project_id, pp.name as parent_project,
                       pc.id as project_id, pc.name as project_name, c.id as category_id, c.name as category_name,
                       SUM(b.sponsorship_total) as weight, MAX(b.due_date) as due_date,
                       b.id, b.handler_id, w.work_type, w.minutes_type, sum(w.minutes) as minutes
                  FROM $t_bug_table b
                  JOIN $t_project_table pc ON b.project_id = pc.id
                  JOIN $t_category_table c ON b.category_id = c.id
                  LEFT OUTER JOIN $t_hierarchy_table h ON pc.id = h.child_id
                  LEFT OUTER JOIN $t_project_table pp ON h.parent_id = pp.id
                  LEFT OUTER JOIN $t_work_table w ON b.id = w.bug_id
                 WHERE (b.target_version = '$f_target_version'";

```
if ( ON == $p_include_bugs_with_deadline ) {
    # First get the release date of the currently targeted version
    $t_query_release_date_target  = "SELECT date_order
                                       FROM $t_project_version_table v
                                      WHERE v.version = '$f_target_version'";
    $t_result_release_date_target = db_query_bound( $t_query_release_date_target );
    $t_release_date_target_array  = db_fetch_array( $t_result_release_date_target );
    $t_release_date_target        = $t_release_date_target_array ? $t_release_date_target_array['date_order'] : time();

    # Next get the release date of the previous version
    $t_query_release_date_previous  = "SELECT max(date_order) as date_order
                                         FROM $t_project_version_table v
                                        WHERE v.date_order < '$t_release_date_target'";
    $t_result_release_date_previous = db_query_bound( $t_query_release_date_previous );
    $t_release_date_previous_array  = db_fetch_array( $t_result_release_date_previous );
    $t_release_date_previous        = $t_release_date_previous_array ? $t_release_date_previous_array['date_order'] : time();

    # It must have been possible to determine both dates in order for this clause to work
    if ( !empty( $t_release_date_target ) && !empty( $t_release_date_previous ) ) {
        # due date is a required field, a value of 1 means no due date
        $t_query .= " OR MAX(b.due_date) BETWEEN $t_release_date_previous AND $t_release_date_target ";
    }
}

$t_query .= ")";

if ( $f_user_id != ALL_USERS ) {
    $t_query .= " AND b.handler_id = $f_user_id";
}

$t_query .= " GROUP BY pp.id, pp.name, pc.id, pc.name, c.id, c.name, b.id, b.handler_id, w.work_type, w.minutes_type
              ORDER BY handler_id, CASE WHEN MAX(b.due_date) = 1 THEN 9999999999 ELSE MAX(b.due_date) END, weight DESC, id";
```

file: billing_page.php
line: 25
$t_query      = "SELECT p.name as project_name, c.name as category_name, u.username,
                        b.id as bug_id, b.summary as bug_summary,
                        sum(w.minutes) as minutes, max(r.hourly_rate) as hourly_rate,
                        max(bc.customers) as customers
                    FROM $t_work_table w
               LEFT JOIN $t_bug_table b ON w.bug_id = b.id
               LEFT JOIN $t_user_table u ON w.user_id = u.id
               LEFT JOIN $t_project_table p ON b.project_id = p.id
               LEFT JOIN $t_category_table c ON b.category_id = c.id
               LEFT OUTER JOIN $t_resource_table r ON w.user_id = r.user_id
               LEFT OUTER JOIN $t_bug_customer_table bc ON b.id = bc.bug_id AND $t_const_paying = bc.type
                   WHERE w.minutes_type = $t_const_done
                     AND w.book_date BETWEEN $t_startdate AND $t_enddate
                   GROUP BY p.name, c.name, u.username, b.id, b.summary
                   ORDER BY p.name, c.name, u.username, b.id, b.summary";

**Comment by vincentsels** [comment]
grishnackh81, could you test with the latest version of the support-mssql branch ? This should include all fixes you just applied yourself. You should just be able to rename your current folder, and copy this new version.
If I missed anything, please re-open this issue - I wasn't able to test it, and that first problem with the LIMIT vs TOP clause is quite tricky - I'm surprised it's not supported by the used data access library!

**Comment by vincentsels** [comment]
Thanks a lot for pinpointing the areas that cause problems and suggesting these fixes btw - saves me a lot of work! :)
Also, feel free to fork & post pull requests! ;)

**Comment by dsienkiewicz** [comment]
OK,
I'll test it as soon as possible.

**Comment by dsienkiewicz** [comment]
Vincent,
now it's much better than was in previous version.
After few test I noticed only one problem:
when I click on Resource progress, I got warning on footer of that page:

SYSTEM WARNING: 'Invalid argument supplied for foreach()' in 'C:\inetpub\wwwroot\mantisbt-1.2.10\plugins\ProjectManagement\classes\PlottableTask.class.php' line 139

Do you know what should I fix to get rid of that message?
