### ISSUE TITLE
Error on billing

### ISSUE THREAD

**Issue by ZoTyA1975** [vincentsels/ProjectManagement#24]
SYSTEM WARNING: 'Division by zero' in '/var/www/clients/client0/web16/web/plugins/ProjectManagement/pages/billing_page.php' line 77

SYSTEM WARNING: 'Division by zero' in '/var/www/clients/client0/web16/web/plugins/ProjectManagement/pages/billing_page.php' line 77

Warnings comes if I add some customers but the issues not added for it.
Maybe it would be nice if I can set customers to projects or subprojects.

**Comment by ZoTyA1975** [comment]
In billing_page.php line 75:
if ( array_search( $cust_id, $t_paying_customers ) !== false && $t_total_percentage != 0 ) {

**Comment by vincentsels** [comment]
Thanks!
