### ISSUE TITLE
JS error on Mantis 1.2.17

### ISSUE THREAD

**Issue by chrsch** [vincentsels/ProjectManagement#35]
I just installed the current ProjectManagement plugin to a new mantis install 1.2.17. For some reason it gives me a JS error on clicking the + symbol in front of the project name in the project progress view.

The error is "ReferenceError: Trim is not defined" in line 6 of the postet JS function from http://mysite/plugin_file.php?file=ProjectManagement/script.js

```
function ShowOrHide(p_div) {
    t_div = document.getElementById(p_div);
    t_expand_icon = document.getElementById(p_div + "_img");

    if (t_div.className.indexOf("hidden") >= 0) {
        t_div.className = Trim(t_div.className.replace("hidden", ""));
        t_expand_icon.src = "images/minus.png";
    } else {
        t_div.className = Trim("hidden " + t_div.className);
        t_expand_icon.src = "images/plus.png";
    }
}
```

Any ideas?

**Comment by chrsch** [comment]
Nevermind, identified and solved the issue. It was a problem with my apache config: http://www.ozonesolutions.com/programming/2012/04/javascript-common-mantis-404-problem-on-ubuntu/

**Comment by vincentsels** [comment]
Thanks for sharing the solution too, for future reference!
