### ISSUE TITLE
Resource Allocation page causes Application Error #401

### ISSUE THREAD

**Issue by keithj-nz** [vincentsels/ProjectManagement#9]
Got this error when I tried "resource Allocation"

APPLICATION ERROR #401 
Database query failed. Error received from database was #1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND 1338811767 ) GROUP BY pp.name, pc.name, c.name, b.id, b.handler_id, w.work_t' at line 8 for the query: SELECT pp.name as parent_project, pc.name as project_name, c.name as category_name, b.id, b.handler_id, w.work_type, w.minutes_type, sum(w.minutes) as minutes
FROM mantis_bug_table b
JOIN mantis_project_table pc ON b.project_id = pc.id
JOIN mantis_category_table c ON b.category_id = c.id
LEFT OUTER JOIN mantis_project_hierarchy_table h ON pc.id = h.child_id
LEFT OUTER JOIN mantis_project_table pp ON h.parent_id = pp.id
LEFT OUTER JOIN mantis_plugin_ProjectManagement_work_table w ON b.id = w.bug_id
WHERE (b.target_version = 'Deployment Version' OR b.due_date BETWEEN AND 1338811767 ) GROUP BY pp.name, pc.name, c.name, b.id, b.handler_id, w.work_type, w.minutes_type.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by vincentsels** [comment]
@keithj-nz It would be great if you could test if this change fixes your issue, so I can close it.

**Comment by keithj-nz** [comment]
I have tested the fix in both a test version of our production database and also a blank fresh install of Mantis.  In both cases no errors where observed.  Haven't figured out what the page actually does yet.

**Comment by vincentsels** [comment]
Thanks for testing. The page displays the total time estimated, done and overdue, per project/category/ticket, for a specific target release.
I'm working on a per-resource view, which should be more interesting I believe. Much like a typical Gantt chart.
